server:
  port: '3000'

logging:
  level:
    root: warn

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  jsp:
    cache: 'false'
  devtools:
    restart:
      enabled: 'true'
    livereload:
      enabled: 'true'
