server:
  port: '3000'

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  jsp:
    cache: 'false'
  devtools:
    restart:
      enabled: 'true'
    livereload:
      enabled: 'true'

backend:
  url: ${BACKEND_URL}