server:
  port: 3000

spring:
  application:
    name: client
  profiles:
    active: local
    #active: deploy
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  jsp:
    cache: 'false'
  devtools:
    restart:
      enabled: 'true'
    livereload:
      enabled: 'true'

backend:
  url: ${BACKEND_URL}

