api:
  user:
    url: ${USER_URL_DEPLOY}
  chat:
    url: ${CHAT_URL_DEPLOY}
  file-storage:
    url: ${FILE_STORAGE_URL_DEPLOY}
  socket-stream:
    url: ${SOCKET_STREAM_URL_DEPLOY}
  gpt-connector:
    url: ${GPT_CONNECTOR_URL_DEPLOY}